version: '3.5'

services:
  fastapi:
    network_mode: host
    build: ../
    command: /bin/bash -c "cd /code/ && pipenv run gunicorn main:app -k uvicorn.workers.UvicornWorker --workers 5 --bind 0.0.0.0:8001"
    # working_dir: /root/
    restart: always
    
