version: '3.5'

services:
  fastapi:
    network_mode: host
    build: ../
    command: /bin/bash -c "cd /code/ && pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8314 --workers 6"
    # working_dir: /root/
    restart: always
    
