version: '3.5'

services:
  django:
    network_mode: host
    build: ../
    command: /bin/bash -c "cd /code/ && pipenv run uvicorn uvicorn main:app --reload --host 0.0.0.0 --port 8314"
    # working_dir: /root/
    restart: always
    
